"""
Phase 3b: LoRA fine-tuning of LLaMA 3.1 8B using Unsloth.

Trains on the SFT dataset generated by prepare_sft_data.py.
Outputs LoRA adapter weights + GGUF for Ollama deployment.
"""

import json
import logging
import yaml
from pathlib import Path

logger = logging.getLogger(__name__)


def load_sft_data(filepath):
    """Load JSONL SFT data into list of message dicts."""
    examples = []
    with open(filepath) as f:
        for line in f:
            examples.append(json.loads(line))
    return examples


def train(config_path="config/paths.yaml"):
    """Run LoRA SFT training."""
    with open(config_path) as f:
        cfg = yaml.safe_load(f)

    sft_cfg = cfg["sft"]
    processed_dir = Path(cfg["processed_dir"])
    model_dir = Path(cfg["model_dir"])
    model_dir.mkdir(parents=True, exist_ok=True)

    # Load dataset
    train_data = load_sft_data(processed_dir / "sft" / "train.jsonl")
    val_data = load_sft_data(processed_dir / "sft" / "val.jsonl")
    logger.info(f"Train: {len(train_data)} examples, Val: {len(val_data)} examples")

    # --- Unsloth setup ---
    from unsloth import FastLanguageModel
    from trl import SFTTrainer
    from transformers import TrainingArguments
    from datasets import Dataset

    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=sft_cfg["base_model"],
        max_seq_length=sft_cfg["max_seq_length"],
        dtype=None,  # auto-detect
        load_in_4bit=sft_cfg.get("load_in_4bit", True),
    )

    model = FastLanguageModel.get_peft_model(
        model,
        r=sft_cfg["lora_r"],
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                        "gate_proj", "up_proj", "down_proj"],
        lora_alpha=sft_cfg["lora_alpha"],
        lora_dropout=sft_cfg["lora_dropout"],
        bias="none",
        use_gradient_checkpointing="unsloth",
    )

    # Format data for SFTTrainer
    def format_example(example):
        messages = example["messages"]
        text = tokenizer.apply_chat_template(messages, tokenize=False)
        return {"text": text}

    train_dataset = Dataset.from_list(train_data).map(format_example)
    val_dataset = Dataset.from_list(val_data).map(format_example)

    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        dataset_text_field="text",
        max_seq_length=sft_cfg["max_seq_length"],
        args=TrainingArguments(
            output_dir=str(model_dir / "checkpoints"),
            per_device_train_batch_size=sft_cfg["batch_size"],
            gradient_accumulation_steps=sft_cfg["gradient_accumulation_steps"],
            num_train_epochs=sft_cfg["epochs"],
            learning_rate=sft_cfg["learning_rate"],
            fp16=True,
            logging_steps=10,
            eval_strategy="steps",
            eval_steps=100,
            save_strategy="steps",
            save_steps=200,
            warmup_steps=50,
            weight_decay=0.01,
            lr_scheduler_type="cosine",
            report_to="none",
        ),
    )

    logger.info("Starting LoRA training...")
    trainer.train()

    # Save LoRA adapter
    adapter_path = model_dir / "llama31-sepsis-lora"
    model.save_pretrained(str(adapter_path))
    tokenizer.save_pretrained(str(adapter_path))
    logger.info(f"Saved LoRA adapter to {adapter_path}")

    # Export to GGUF for Ollama
    gguf_path = model_dir / "llama31-sepsis.gguf"
    logger.info(f"Exporting GGUF to {gguf_path}")
    model.save_pretrained_gguf(
        str(gguf_path.parent / gguf_path.stem),
        tokenizer,
        quantization_method="q4_k_m",
    )
    logger.info("GGUF export complete")

    return adapter_path, gguf_path


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    train()
